<?php
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz 
	 */
	 
	namespace src\model; 
	
	use src\model;
	
	class TelasDao {
	
		private $connection;
		
		/*
		 * Constant variables
		 */
		private $create = "INSERT INTO telas (
				tela
				, identificador
				, cadastrado
				, modificado
				, menu
				) VALUES";
				
		public $read = 
				"telas.id AS \"telas.id\"
				, telas.tela AS \"telas.tela\"
				, telas.identificador AS \"telas.identificador\"
				, telas.cadastrado AS \"telas.cadastrado\"
				, telas.modificado AS \"telas.modificado\"
				, telas.menu AS \"telas.menu\"
				";
				
		private $update = "UPDATE telas SET";
		private $delete = "DELETE FROM telas";
		
		public $from = "telas telas";
		
		/*
		 * Parameters
		 */
		private $where;
		private $order;
		
		// Dynamic query
		private $sql;
		
		// Controller response
		private $response;	
		
		/**
		 * @param {Object} connection
		 */
		public function __construct($connection) {
			$this->connection = $connection;
		}

		/**
		 * @param {Telas}telas
		 */
		public function setCreate($telas) {		
			$this->sql = $this->create . " (\"" . 
					$telas->getTela() .
					"\", \"" . $telas->getIdentificador() .
					"\", \"" . $telas->getCadastrado() .
					"\", \"" . $telas->getModificado() .
					"\", \"" . $telas->getMenu() .
					"\")";
		}
		
		/**
		 * @return {String}
		 */
		public function getCreate() {
			return $this->sql;
		}	
		
		/**
		 * @param {String} where
		 * @param {String} order
		 */
		public function setRead($where, $order) {
			$menusDao = new model\MenusDao($this->connection);
			
			$this->setWhere($where);
			$this->setOrder($order);
			
			$this->sql = "SELECT " . $this->read . ", " . $menusDao->read . 
					" FROM " . $this->getFrom() .", " . $menusDao->from . 
					($this->getWhere() == "" ? " WHERE telas.menu = menus.id" : $this->getWhere()) . 
					" AND telas.menu = menus.id" . $this->getOrder();
		}
		
		/**
		 * @return {String}
		 */
		public function getRead() {
			return $this->sql;
		}
		
		/**
		 * @param {Telas}telas  
		 * @param {String} where
		 */
		public function setUpdate($telas, $where) {
			$this->setWhere($where);
			
			$this->sql = $this->update . 
					" id = \"" . $telas->getId() . 
					"\", tela = \"" . $telas->getTela() . 
					"\", identificador = \"" . $telas->getIdentificador() . 
					"\", modificado = \"" . $telas->getModificado() . 
					"\", menu = \"" . $telas->getMenu() . 
					"\"" . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getUpdate() {
			return $this->sql;
		}
		
		/**
		 * @param {String} where
		 */
		public function setDelete($where) {	
			$this->setWhere($where);
			
			$this->sql = $this->delete . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getDelete() {
			return $this->sql;
		}
		
		/**
		 * @return {String}
		 */
		public function getFrom() {
			return $this->from;
		}
		
		/**
		 * @param {String} where
		 */
		public function setWhere($where) {
			if ($where != "")
				$this->where = " WHERE " . $where;
			else
				$this->where = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getWhere() {
			return $this->where;
		}
		
		/**
		 * @param {String} order
		 */
		public function setOrder($order) {
			if ($order != "")
				$this->order = " ORDER BY " . $order;
			else
				$this->order = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getOrder() {
			return $this->order;
		}
		
		/**
		 * @param {Integer} line
		 * @param column String
		 * @param value String
		 */
		private function setResponse($line, $column, $value) {
			$this->response[$line][$column] = $value;
		}

		/**
		 * @return {Array}
		 */
		private function getResponse() {
			return $this->response;
		}

		/**
		 * @param {String} where
		 */
		private function setSize($where) {
			$this->setWhere($where);
			
			$result = $this->connection->execute(
					"SELECT count(1) AS \"telas.size\" from telas" . $this->getWhere());

			while ($row = $result->fetch_assoc()) {		
				$this->setResponse(0, "telas.size", $row["telas.size"]);
				
				$pages = ceil($row["telas.size"] / $this->connection->getItensPerPage());
				
				$this->setResponse(0, "telas.page", $this->connection->getPosition());
				$this->setResponse(0, "telas.pages", $pages);
				
				$pagination = "<select id='gz-select-pagination' onchange='goPage();'>";
				
				for ($i = 1; $i <= $pages; $i++) {
					if ($i == $this->connection->getPosition())
						$pagination .= "<option value='" . $i . "' selected>" . $i . "</option>";
					else
						$pagination .= "<option value='" . $i . "'>" . $i . "</option>";
				}	

				$pagination .= "</select>";
						
				$this->setResponse(0, "telas.pagination", $pagination);
			}

			$this->connection->free($result);
		}
		
		/**
		 * @param {Integer} line
		 */
		public function setDivLine($line) {
			$this->setResponse($line - 1, "@_START_LINE_TWO", modelStartLine($line, 2));
			$this->setResponse($line - 1, "@_END_LINE_TWO", modelEndLine($line, 2));

			$this->setResponse($line - 1, "@_START_LINE_THREE", modelStartLine($line, 3));
			$this->setResponse($line - 1, "@_END_LINE_THREE", modelEndLine($line, 3));
			
			$this->setResponse($line - 1, "@_START_LINE_FOUR", modelStartLine($line, 4));
			$this->setResponse($line - 1, "@_END_LINE_FOUR", modelEndLine($line, 4));
		}
		
		/**
		 * @param {Integer} line
		 */
		public function checkDivLine($line) {
			if (modelCheckEndLine($line, 2) != "")
				$this->setResponse($line - 1, "@_END_LINE_TWO", modelCheckEndLine($line, 2));
			
			if (modelCheckEndLine($line, 3) != "")
				$this->setResponse($line - 1, "@_END_LINE_THREE", modelCheckEndLine($line, 3));		

			if (modelCheckEndLine($line, 4) != "")
				$this->setResponse($line - 1, "@_END_LINE_FOUR", modelCheckEndLine($line, 4));			
		}	

		/**
		 * @param {String} log
		 */
		private function setLog($log) {
			$this->setResponse(0, "log", $log);
		}
		
		/**
		 * @param {Telas} telas 
		 * @return {Boolean}
		 */
		public function create($telas) {
			$result = "";

			$this->setCreate($telas);
			$result = $this->connection->execute($this->getCreate());
			
			return $result;
		}

		/**
		 * @param {String} where
		 * @param {String} order
		 * @param {Boolean} wp
		 * @param {Array}
		 */
		public function read($where, $order, $wp) {
			$line = 0;

			$this->setRead($where, $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($line, "telas.id", $row["telas.id"]);
				$this->setResponse($line, "telas.tela", $row["telas.tela"]);
				$this->setResponse($line, "telas.tela.format", modelDoubleQuotes($row["telas.tela"]));
				$this->setResponse($line, "telas.tela.view", addLine($row["telas.tela"]));
				$this->setResponse($line, "telas.identificador", $row["telas.identificador"]);
				$this->setResponse($line, "telas.identificador.format", modelDoubleQuotes($row["telas.identificador"]));
				$this->setResponse($line, "telas.cadastrado", modelDateTime($row["telas.cadastrado"]));
				$this->setResponse($line, "telas.modificado", modelDateTime($row["telas.modificado"]));
				$this->setResponse($line, "telas.menu", $row["telas.menu"]);
				$this->setResponse($line, "menus.menu", $row["menus.menu"]);
			
				$this->setResponse($line, "telas.line", $line);
			
				$line++;
				
				if ($wp)
					$this->setDivLine($line);
			}

			$this->connection->free($result);
			
			if ($wp && $line > 0) {
				$this->checkDivLine($line);
				
				$this->setSize($where);
			}

			return $this->getResponse();
		}

		/**
		 * @param {Telas} telas 
		 * @return {Boolean}
		 */
		public function update($telas) {
			$result = "";
			
			$this->setUpdate($telas, "telas.id = " . $telas->getId());
			$result = $this->connection->execute($this->getUpdate());

			return $result;
		}

		/**
		 * @param {String} where
		 * @return {Boolean}
		 */
		public function delete($where) {
			$result = "";
			
			$this->setDelete($where);
			$result = $this->connection->execute($this->getDelete());

			return $result;
		}
		
		/**
		 * @param {Integer} selected
		 * @param {String} order
		 * @return {Array}
		 */
		public function combo($selected, $order) {
			$size = 0;

			$this->setRead("", $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "telas.id", $row["telas.id"]);
				$this->setResponse($size, "telas.tela", $row["telas.tela"]);
			
				if ($row["telas.id"] == $selected)
					$this->setResponse($size, "telas.selected", "selected");
				else
					$this->setResponse($size, "telas.selected", "");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}
		
		/**
		 * @param {String} where
		 * @return {Array}
		 */
		public function comboScr($where) {
			$size = 0;

			$this->setRead($where, "");
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "telas.id", $row["telas.id"]);
				$this->setResponse($size, "telas.tela", $row["telas.tela"]);
				$this->setResponse($size, "telas.selected", "selected");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}

	}

?>