<?php 
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz
	 */
	 
	namespace src\model; 

	class Telas {
			
		private $id;
		private $tela;
		private $identificador;
		private $cadastrado;
		private $modificado;
		private $menu;
			
		public function __construct() { }
			
		public function setId($id) {
			$this->id = $id;
		}
		
		public function getId() {
			return $this->id;
		}
					
		public function setTela($tela) {
			$this->tela = $tela;
		}
		
		public function getTela() {
			return $this->tela;
		}
					
		public function setIdentificador($identificador) {
			$this->identificador = $identificador;
		}
		
		public function getIdentificador() {
			return $this->identificador;
		}
					
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
		
		public function getCadastrado() {
			return $this->cadastrado;
		}
					
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
		
		public function getModificado() {
			return $this->modificado;
		}
					
		public function setMenu($menu) {
			$this->menu = $menu;
		}
		
		public function getMenu() {
			return $this->menu;
		}
					
	}
	
?>