<?php

	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz
	 */

	use lib\getz;
	use src\model;	 
	 
	require_once($_DOCUMENT_ROOT . "/lib/getz/Activator.php");

	if ($method == "page") {
		$darth->setTitle(ucfirst($screen));
		$darth->setDescription("");
		$darth->setKeywords("");
		if (isset($_GET["friendly"])) {
			$token = base64_decode($_GET["friendly"]);
			$tokenMath = explode("g3tz", $token);
			$userId = ($tokenMath[1] / 128) - 32;
			$daoFactory->beginTransaction();
			$usuariosDao = $daoFactory->getUsuariosDao()->read("usuarios.id = " . $userId . 
					" AND usuarios.situacao_registro = 2", "usuarios.id ASC", true);
			if (is_array($usuariosDao) && sizeof($usuariosDao) > 0) {
				$usuarios = new model\Usuarios();
				$usuarios->setId($userId);
				$usuarios->setUsuario($usuariosDao[0]["usuarios.usuario"]);
				$usuarios->setCpf($usuariosDao[0]["usuarios.cpf"]);
				$usuarios->setData_nascimento(controllerDate($usuariosDao[0]["usuarios.data_nascimento"]));
				$usuarios->setCelular($usuariosDao[0]["usuarios.celular"]);
				$usuarios->setEmail($usuariosDao[0]["usuarios.email"]);
				$usuarios->setSenha($usuariosDao[0]["usuarios.senha"]);
				$usuarios->setFoto("");
				$usuarios->setActivation_token("");
				$usuarios->setActivation_token_expiration("0000-00-00 00:00:00");
				$usuarios->setPassword_token("");
				$usuarios->setPassword_token_expiration("0000-00-00 00:00:00");
				$usuarios->setAccess_token("");
				$usuarios->setAccess_token_expiration("0000-00-00 00:00:00");
				$usuarios->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
				$usuarios->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
				$usuarios->setPerfil($usuariosDao[0]["usuarios.perfil"]);
				$usuarios->setSituacao_registro(1);
				$resultDao = $daoFactory->getUsuariosDao()->update($usuarios);
				if ($resultDao) {
					$daoFactory->commit();
					$response[0]["message"] = "success";
				} else {							
					$daoFactory->rollback();
					$response[0]["message"] = "error";
				}
			} else {
				$response[0]["message"] = "error";
			}
			echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/head.html");
			echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/ativar_a_minha_conta.html");
			echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/foot.html");
		}
	}
?>