<?php

	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz
	 */

	use lib\getz;
	use src\model;	 
	 
	require_once($_DOCUMENT_ROOT . "/lib/getz/Activator.php");

	if ($method == "page") {
		$token = base64_decode($_COOKIE[$_PROJECT]);
		$tokenMath = explode("g3tz", $token);
		$id = ($tokenMath[1] / 128) - 32;
		$daoFactory->beginTransaction();
		$response[0]["usuarios"] = $daoFactory->getUsuariosDao()->read("usuarios.id = " . $id . 
				" AND usuarios.situacao_registro = 1", "usuarios.id ASC", true);
		$daoFactory->close();
		if (is_array($response[0]["usuarios"]) && sizeof($response[0]["usuarios"]) > 0) {			
			header("Location: " . $darth->getRoot() . "/inicio");
		} else {
			$darth->setTitle(ucfirst($screen));
			$darth->setDescription("");
			$darth->setKeywords("");
			echo $darth->view("", $_DOCUMENT_ROOT . $_PACKAGE . "/html/header.html");
			echo $darth->view("", $_DOCUMENT_ROOT . $_PACKAGE . "/html/home.html");
			echo $darth->view("", $_DOCUMENT_ROOT . $_PACKAGE . "/html/footer.html");
		}
	}

?>