<?php

	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz
	 */

	use lib\getz;
	use src\model;	

	require_once($_DOCUMENT_ROOT . "/lib/getz/Activator.php");
	
	if ($method == "page") {
		$token = base64_decode($_COOKIE[$_PROJECT]);
		$tokenMath = explode("g3tz", $token);
		$id = ($tokenMath[1] / 128) - 32;
		$daoFactory->beginTransaction();
		$response[0]["usuarios"] = $daoFactory->getUsuariosDao()->read("usuarios.id = " . $id . 
				" AND usuarios.situacao_registro = 1", "usuarios.id ASC", true);
		$daoFactory->close();
		if (is_array($response[0]["usuarios"]) && sizeof($response[0]["usuarios"]) > 0) {
			$darth->setTitle(ucfirst($screen));
			$darth->setDescription("");
			$darth->setKeywords("");				
			echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/header.html");
			echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/side.html");
			echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/minha_conta.html");			
			echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/footer.html");			
		} else {
			header("Location: " . $darth->getRoot() . "/home");
		}		
	} else if (!getActiveSession($_ROOT . $_MODULE)) {
		echo "<script>goTo(\"/login/1\");</script>";
	} else {
		if ($method == "update") {
			$daoFactory->beginTransaction();
			$data = $daoFactory->getUsuariosDao()->read("usuarios.id = " . $session[0]["usuarios.id"], "", false);
			if (md5(logicNull($form[1])) == $data[0]["usuarios.senha"]) {
				$usuarios = new model\Usuarios();
				$usuarios->setId($data[0]["usuarios.id"]);
				$usuarios->setUsuario(logicNull($form[0]));
				$usuarios->setEmail($data[0]["usuarios.email"]);
				$usuarios->setSenha(md5(logicNull($form[2])));
				$usuarios->setFoto(($data[0]["usuarios.foto"] == "../male-user.svg" || 
						$data[0]["usuarios.foto"] == "../female-user.svg") ? "" : $data[0]["usuarios.foto"]);
				$usuarios->setAccess_token($data[0]["usuarios.access_token"]);	
				$usuarios->setAccess_token_expiration(controllerDatetime($data[0]["usuarios.access_token_expiration"]));	
				$usuarios->setActivation_token($data[0]["usuarios.activation_token"]);	
				$usuarios->setActivation_token_expiration(controllerDatetime(
						$data[0]["usuarios.activation_token_expiration"]));	
				$usuarios->setPassword_token($data[0]["usuarios.password_token"]);	
				$usuarios->setPassword_token_expiration(controllerDatetime(
						$data[0]["usuarios.password_token_expiration"]));								
				$usuarios->setCadastrado(date("Y-m-d H:i:s"));
				$usuarios->setModificado(date("Y-m-d H:i:s"));
				$usuarios->setPerfil($data[0]["usuarios.perfil"]);
				$usuarios->setSituacao_registro($data[0]["usuarios.situacao_registro"]);
				$resultDao = $daoFactory->getUsuariosDao()->update($usuarios);
				if ($resultDao) {
					$daoFactory->commit();
					$response[0]["message"] = "success";
				} else {							
					$daoFactory->rollback();
					$response[0]["message"] = "error";
				}	
			} else {
				$response[0]["message"] = "error";
			}
			$daoFactory->close();
			echo $darth->json($response);
		} else if ($method == "stateRead") {		
			$daoFactory->beginTransaction();
			$response[0]["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", 
					true);
			$response[0]["usuarios"] = $daoFactory->getUsuariosDao()->read("usuarios.id = " . 
					$session[0]["usuarios.id"], "", true);
			$daoFactory->close();
			echo $darth->view(getMenu($daoFactory, $_USER, $screen), $_DOCUMENT_ROOT . $_PACKAGE . 
					"/html/menus/menusCST.html");
			echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/minha_conta/minha_contaCST.html");
		}
	}
	
?>