<?php

	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz
	 */

	use lib\getz;
	use src\model;	

	require_once($_DOCUMENT_ROOT . "/lib/getz/Activator.php");
	
	if (!getActiveSession($_ROOT . $_MODULE)) {
		echo "<script>goTo(\"/login/1\");</script>";
	} else {
		if ($method == "update") {
			$daoFactory->beginTransaction();
			$data = $daoFactory->getUsuariosDao()->read("usuarios.id = " . $session[0]["usuarios.id"], "", false);
			$usuarios = new model\Usuarios();
			$usuarios->setId($data[0]["usuarios.id"]);
			$usuarios->setUsuario($data[0]["usuarios.usuario"]);
			$usuarios->setEmail($data[0]["usuarios.email"]);
			$usuarios->setSenha($data[0]["usuarios.senha"]);
			if (isset($_FILES["upload"])) {
				if ($data[0]["usuarios.foto"] != "" && $data[0]["usuarios.foto"] != "../male-user.svg" && 
						$data[0]["usuarios.foto"] == "../female-user.svg") {	
					unlink($_DOCUMENT_ROOT . "/res/img/ldpi/" . $data[0]["usuarios.foto"]);	
					unlink($_DOCUMENT_ROOT . "/res/img/mdpi/" . $data[0]["usuarios.foto"]);
					unlink($_DOCUMENT_ROOT . "/res/img/hdpi/" . $data[0]["usuarios.foto"]);
				}
				$upload = new getz\Upload($_FILES["upload"], 640);
				$usuarios->setFoto($upload->getName());
			} else {
				$usuarios->setFoto(($data[0]["usuarios.foto"] == "../male-user.svg" || 
						$data[0]["usuarios.foto"] == "../female-user.svg") ? "" : $data[0]["usuarios.foto"]);
			}
			$usuarios->setAccess_token($data[0]["usuarios.access_token"]);
			$usuarios->setAccess_token_expiration(controllerDatetime($data[0]["usuarios.access_token_expiration"]));
			$usuarios->setActivation_token($data[0]["usuarios.activation_token"]);
			$usuarios->setActivation_token_expiration(controllerDatetime(
					$data[0]["usuarios.activation_token_expiration"]));
			$usuarios->setPassword_token($data[0]["usuarios.password_token"]);
			$usuarios->setPassword_token_expiration(controllerDatetime(
					$data[0]["usuarios.password_token_expiration"]));
			$usuarios->setCadastrado(date("Y-m-d H:i:s"));
			$usuarios->setModificado(date("Y-m-d H:i:s"));
			$usuarios->setPerfil($data[0]["usuarios.perfil"]);
			$usuarios->setSituacao_registro($data[0]["usuarios.situacao_registro"]);
			$resultDao = $daoFactory->getUsuariosDao()->update($usuarios);
			if ($resultDao) {
				$daoFactory->commit();
				$response[0]["message"] = "success";
			} else {							
				$daoFactory->rollback();
				$response[0]["message"] = "error";
			}	
			$daoFactory->close();
			echo $darth->json($response);
		} else if ($method == "stateRead") {		
			$daoFactory->beginTransaction();
			$response[0]["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", 
					true);
			$response[0]["usuarios"] = $daoFactory->getUsuariosDao()->read("usuarios.id = " . 
					$session[0]["usuarios.id"], "", true);
			$daoFactory->close();
			echo $darth->view(getMenu($daoFactory, $_USER, $screen), $_DOCUMENT_ROOT . $_PACKAGE . 
					"/html/menus/menusCST.html");
			echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/mudar_foto/mudar_fotoCST.html");
		}
	}

?>