<?php

	/**
	 * Generated by Getz Framework
	 *
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz
	 */
	 
	use lib\getz;
	use src\model;	 

	require_once($_DOCUMENT_ROOT . "/lib/getz/Activator.php");
	
	/*
	 * Filters
	 */
	$where = "";
	
	if ($search != "")
		$where = "perfil_tela.modificado LIKE \"%" . $search . "%\"";	
		
	if ($code != "")
		$where = "perfil_tela.id = " . $code;
	
	if (isset($_GET["friendly"]))
		$where = "perfil_tela.modificado = \"" . removeLine($_GET["friendly"]) . "\"";	
		
	$limit = "";	
		
	if ($order != "") {
		$o = explode("<gz>", $order);

		$limit = $o[0] . " " . $o[1] . " LIMIT " . 
				(($position * $itensPerPage) - $itensPerPage) . ", " . $itensPerPage;
				
	} else {
		if ($position > 0 && $itensPerPage > 0) {
			$limit = "perfil_tela.id DESC LIMIT " . 
					(($position * $itensPerPage) - $itensPerPage) . ", " . $itensPerPage;	
		}
	}
	
	/**************************************************
	 * Webpage
	 **************************************************/		
	
	/*
	 * Page
	 */
	if ($method == "page") {
		/*
		 * SEO
		 */
		$darth->setTitle(ucfirst($screen));
		$darth->setDescription("");
		$darth->setKeywords("");
		
		$daoFactory->beginTransaction();
		$response[0]["perfil_tela"] = $daoFactory->getPerfil_telaDao()->read($where, $limit, true);
		$daoFactory->close();
		
		if (isset($_GET["friendly"]))
			$darth->setTitle($response[0]["perfil_tela"][0]["perfil_tela.modificado"]);

		echo $darth->view("", $_DOCUMENT_ROOT . $_PACKAGE . "/html/header.html");
		
		echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . 
				(isset($_GET["friendly"]) ? "/html/@_PAGE.html" : "/html/perfil_tela.html"));
		
		echo $darth->view("", $_DOCUMENT_ROOT . $_PACKAGE . "/html/footer.html");
	}
	
	/**************************************************
	 * Webservice
	 **************************************************/	

	/*
	 * Create
	 */
	else if ($method == "api-create") {
		enableCORS();
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			// $request[0]["@_PARAM"] = $daoFactory->prepare($request[0]["@_PARAM"]); // Prepare with sql injection.

			$daoFactory->beginTransaction();
			$perfil_tela = new model\Perfil_tela();
			$perfil_tela->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$perfil_tela->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$perfil_tela->setPerfil($request["perfil_tela.perfil"]);
			$perfil_tela->setTela($request["perfil_tela.tela"]);
			$perfil_tela->setPermissao($request["perfil_tela.permissao"]);
			
			$resultDao = $daoFactory->getPerfil_telaDao()->create($perfil_tela);

			if ($resultDao) {
				$daoFactory->commit();
				$response[0]["message"] = "success";
			} else {							
				$daoFactory->rollback();
				$response[0]["message"] = "error";
			}

			$daoFactory->close();
		} else {
			$response[0]["message"] = "error";
		}
		
		echo $darth->json($response);
	}
	
	/*
	 * Read
	 */
	else if ($method == "api-read") {
		enableCORS();
		
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			
			$limit = "perfil_tela.id DESC LIMIT " . 
					(($request[0]["page"] * $request[0]["pageSize"]) - 
					$request[0]["pageSize"]) . ", " . $request[0]["pageSize"];	
		}
		
		$daoFactory->beginTransaction();
		$perfil_tela = $daoFactory->getPerfil_telaDao()->read("", $limit, false);
		$daoFactory->close();
		
		echo $darth->json($perfil_tela);
	}
	
	/*
	 * Update
	 */
	else if ($method == "api-update") {	
		enableCORS();
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			// $request[0]["@_PARAM"] = $daoFactory->prepare($request[0]["@_PARAM"]); // Prepare with sql injection.
			
			$perfil_tela = new model\Perfil_tela();
			$perfil_tela->setId($request["perfil_tela.id"]);
			$perfil_tela->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$perfil_tela->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$perfil_tela->setPerfil($request["perfil_tela.perfil"]);
			$perfil_tela->setTela($request["perfil_tela.tela"]);
			$perfil_tela->setPermissao($request["perfil_tela.permissao"]);
			
			$daoFactory->beginTransaction();
			$resultDao = $daoFactory->getPerfil_telaDao()->update($perfil_tela);

			if ($resultDao) {
				$daoFactory->commit();
				$response[0]["message"] = "success";
			} else {							
				$daoFactory->rollback();
				$response[0]["message"] = "error";
			}

			$daoFactory->close();
		} else {
			$response[0]["message"] = "error";
		}
		
		echo $darth->json($response);
	}
	
	/* 
	 * Delete
	 */
	else if ($method == "api-delete") {
		enableCORS();
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			$request["perfil_tela.id"] = $daoFactory->prepare($request["perfil_tela.id"]); // Prepare with sql injection.
				
			$result = true;
			$lines = explode("<gz>", $request["perfil_tela.id"]);

			$daoFactory->beginTransaction();

			for ($i = 0; $i < sizeof($lines); $i++) {
				$where = "perfil_tela.id = " . $lines[$i];
				
				$resultDao = $daoFactory->getPerfil_telaDao()->delete($where);
				$result = !$result ? false : (!$resultDao ? false : true);
			}

			if ($result) {
				$daoFactory->commit();
				$response[0]["message"] = "success";
			} else {							
				$daoFactory->rollback();
				$response[0]["message"] = "error";
			}

			$daoFactory->close();
		} else {
			$response[0]["message"] = "error";
		} 

		echo $darth->json($response);
	}
	
	/**************************************************
	 * System
	 **************************************************/	
	
	else {
		if (!getActiveSession($_ROOT . $_MODULE)) 
			echo "<script>goTo(\"/login/1\");</script>";
		else {
			/*
			 * Create
			 */
			if ($method == "stateCreate") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response[0]["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response[0]["perfis"] = $daoFactory->getPerfisDao()->read("", "perfis.id ASC", false);
					$response[0]["telas"] = $daoFactory->getTelasDao()->read("", "telas.id ASC", false);
					$response[0]["permissoes"] = $daoFactory->getPermissoesDao()->read("", "permissoes.id ASC", false);
					$daoFactory->close();

					echo $darth->view(getMenu($daoFactory, $_USER, $screen), $_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html");
					echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/perfil_tela/perfil_telaCRT.html");
				}
			}

			/*
			 * Read
			 */
			else if ($method == "stateRead") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response[0]["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response[0]["perfil_tela"] = $daoFactory->getPerfil_telaDao()->read($where, $limit, true);
					if (!is_array($response[0]["perfil_tela"])) {
						$response[0]["data_not_found"][0]["value"] = "<p>Não possui registro.</p>";
					}
					$daoFactory->close();

					echo $darth->view(getMenu($daoFactory, $_USER, $screen), $_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html");
					echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/perfil_tela/perfil_telaRD.html");
				}
			}

			/*
			 * Update
			 */
			else if ($method == "stateUpdate") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response[0]["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response[0]["perfil_tela"] = $daoFactory->getPerfil_telaDao()->read($where, "", true);
					$response[0]["perfil_tela"][0]["perfil_tela.perfis"] = $daoFactory->getPerfisDao()->read("", "perfis.id ASC", false);
					for ($x = 0; $x < sizeof($response[0]["perfil_tela"][0]["perfil_tela.perfis"]); $x++) {
						if ($response[0]["perfil_tela"][0]["perfil_tela.perfis"][$x]["perfis.id"] == 
								$response[0]["perfil_tela"][0]["perfil_tela.perfil"]) {
							$response[0]["perfil_tela"][0]["perfil_tela.perfis"][$x]["perfis.selected"] = "selected";
						}
					}
					$response[0]["perfil_tela"][0]["perfil_tela.telas"] = $daoFactory->getTelasDao()->read("", "telas.id ASC", false);
					for ($x = 0; $x < sizeof($response[0]["perfil_tela"][0]["perfil_tela.telas"]); $x++) {
						if ($response[0]["perfil_tela"][0]["perfil_tela.telas"][$x]["telas.id"] == 
								$response[0]["perfil_tela"][0]["perfil_tela.tela"]) {
							$response[0]["perfil_tela"][0]["perfil_tela.telas"][$x]["telas.selected"] = "selected";
						}
					}
					$response[0]["perfil_tela"][0]["perfil_tela.permissoes"] = $daoFactory->getPermissoesDao()->read("", "permissoes.id ASC", false);
					for ($x = 0; $x < sizeof($response[0]["perfil_tela"][0]["perfil_tela.permissoes"]); $x++) {
						if ($response[0]["perfil_tela"][0]["perfil_tela.permissoes"][$x]["permissoes.id"] == 
								$response[0]["perfil_tela"][0]["perfil_tela.permissao"]) {
							$response[0]["perfil_tela"][0]["perfil_tela.permissoes"][$x]["permissoes.selected"] = "selected";
						}
					}
					$daoFactory->close();

					echo $darth->view(getMenu($daoFactory, $_USER, $screen), $_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html");
					echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/perfil_tela/perfil_telaUPD.html");
				}
			}

			/*
			 * Called
			 */
			else if ($method == "stateCalled") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					/*
					 * Insert your foreign key here
					 */
					if ($where != "")
						$where .= " AND perfil_tela.@_FOREIGN_KEY = " . $base;
					else 
						$where = "perfil_tela.@_FOREIGN_KEY = " . $base;
						
					$daoFactory->beginTransaction();
					$response[0]["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response[0]["perfil_tela"] = $daoFactory->getPerfil_telaDao()->read($where, $limit, true);
					if (!is_array($response[0]["perfil_tela"])) {
						$response[0]["data_not_found"][0]["value"] = "<p>Não possui registro.</p>";
					}
					$daoFactory->close();

					echo $darth->view(getMenu($daoFactory, $_USER, $screen), $_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html");
					echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/perfil_tela/perfil_telaCLL.html");
				}
			}

			/*
			 * Screen
			 */
			else if ($method == "screen") {
				if ($base != "") {
					$arrBase = explode("<gz>", $base);
					
					if (sizeof($arrBase) > 1) {
						if ($where != "")
							$where .= " AND perfil_tela.@_FOREIGN_KEY = " . $arrBase[1];
						else
							$where = "perfil_tela.@_FOREIGN_KEY = " . $arrBase[1];
					}
				}
				
				$limit = "perfil_tela.id DESC LIMIT " . (($position * 5) - 5) . ", 5";

				$daoFactory->beginTransaction();
				$response[0]["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
				$response[0]["perfil_tela"] = $daoFactory->getPerfil_telaDao()->read($where, $limit, true);
				$daoFactory->close();

				echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/perfil_tela/perfil_telaSCR.html") . 
						"<size>" . (is_array($response[0]["perfil_tela"]) ? $response[0]["perfil_tela"][0]["perfil_tela.size"] : 0) . "<theme>455a64";
			}

			/*
			 * Screen handler
			 */
			else if ($method == "screenHandler") {	
				$where = "";

				// Get value from combo
				$cmb = explode("<gz>", $search);

				if ($cmb[1] != "")
					$where = "perfil_tela.id = " . $cmb[1];

				$daoFactory->beginTransaction();
				$response[0]["perfil_tela"] = $daoFactory->getPerfil_telaDao()->comboScr($where);
				$daoFactory->close();

				echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/perfil_tela/perfil_telaCMB.html");
			}

			/*
			 * Create
			 */
			else if ($method == "create") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response[0]["message"] = "permission";
					
					echo $darth->json($response);
				} else {
					$perfil_tela = new model\Perfil_tela();
					$perfil_tela->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$perfil_tela->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$perfil_tela->setPerfil($form[0]);
					$perfil_tela->setTela($form[1]);
					$perfil_tela->setPermissao($form[2]);
					
					$daoFactory->beginTransaction();
					$resultDao = $daoFactory->getPerfil_telaDao()->create($perfil_tela);

					if ($resultDao) {
						$daoFactory->commit();
						$response[0]["message"] = "success";				
					} else {							
						$daoFactory->rollback();
						$response[0]["message"] = "error";
					}

					$daoFactory->close();

					echo $darth->json($response);
				}
			}

			/*
			 * Action update
			 */
			else if ($method == "update") {	
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response[0]["message"] = "permission";
					
					echo $darth->json($response);
				} else {
					$perfil_tela = new model\Perfil_tela();
					$perfil_tela->setId($code);
					$perfil_tela->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$perfil_tela->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$perfil_tela->setPerfil($form[0]);
					$perfil_tela->setTela($form[1]);
					$perfil_tela->setPermissao($form[2]);
					
					$daoFactory->beginTransaction();
					$resultDao = $daoFactory->getPerfil_telaDao()->update($perfil_tela);

					if ($resultDao) {
						$daoFactory->commit();
						$response[0]["message"] = "success";
					} else {							
						$daoFactory->rollback();
						$response[0]["message"] = "error";
					}

					$daoFactory->close();

					echo $darth->json($response);
				}
			}
			
			/* 
			 * Action delete
			 */
			else if ($method == "delete") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response[0]["message"] = "permission";
					
					echo $darth->json($response);
				} else {
					$result = true;
					$lines = explode("<gz>", $code);

					$daoFactory->beginTransaction();

					for ($i = 1; $i < sizeof($lines); $i++) {
						$where = "perfil_tela.id = " . $lines[$i];
						
						$resultDao = $daoFactory->getPerfil_telaDao()->delete($where);
						$result = !$result ? false : (!$resultDao ? false : true);
					}

					if ($result) {
						$daoFactory->commit();
						$response[0]["message"] = "success";
					} else {							
						$daoFactory->rollback();
						$response[0]["message"] = "error";
					}

					$daoFactory->close();

					echo $darth->json($response);	
				}
			}
		}
	}

?>